"""Test corpus for detector 008 (hardcoded secrets).

Each case is labelled with its expected verdict.
Do not edit this file to make the detector pass.
"""


# ======================================================================
# HIGH -- a real credential
# ======================================================================

# [HIGH] known credential format (Stripe-style live key)
api_key = "sk-live-51H8xReAbc123Def456"

# [HIGH] secret-named target + real-looking value (no known format)
password = "9xK$mP2vLq8wNz"

# [HIGH] PEM private key material
private_key = "-----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEA7f9k"

# [HIGH] known format, GitHub personal access token
gh_token = "ghp_16C7e42F292c6912E7710c838347Ae178B4a"


# ======================================================================
# REVIEW -- ambiguous
# ======================================================================

# [REVIEW] secret-named target, low-ish entropy, no known format
secret = "abc123"

# [REVIEW] high-entropy value in a NON-secret target (good-faith catch)
config_value = "x8Fk2Lm9Qp"


# ======================================================================
# SILENT -- placeholders (step 1 kills these before scoring)
# ======================================================================

# [silent] template placeholder despite the secret-named target
api_key_template = "YOUR_KEY_HERE"

# [silent] placeholder word
default_password = "example"

# [silent] placeholder word
session_token = "test"

# [silent] AWS's own DOCUMENTED example key. It carries the real AKIA prefix,
# but step 1 (placeholder) runs BEFORE step 2 (known format), and a published
# example is a placeholder that happens to be well-formed. The ORDERING is the
# rule, and it resolves this case to SILENT.
AWS_KEY = "AKIAIOSFODNN7EXAMPLE"


# ======================================================================
# SILENT -- ordinary strings (the flood test)
# ======================================================================

name = "Alice"

# [silent] the spec's literal example URL -- the "example" marker makes step 1
# fire, so this is silent for a reason unrelated to it being a URL.
url_example = "https://api.example.com"

# [silent] a realistic internal URL: no placeholder marker, but URI-shaped, so
# the step-3 shape gate rejects it before entropy scoring. (Was REVIEW.)
url = "https://api.internal.corp/v2"

# [silent] a filesystem path -- path-shaped. (Was the same gap.)
db_path = "/var/lib/app/data.db"

# [silent] a connection string with NO embedded credential, non-secret target
config = "postgres://localhost:5432/mydb"

path = "/etc/config"
greeting = "hello world"


# ======================================================================
# THE SHAPE GATE MUST NOT OVER-REJECT
# ======================================================================

# [HIGH] base64-ish secret CONTAINING slashes but NOT path-shaped. The gate is
# structural (leading shape), never "contains a slash", so this still flags.
api_key = "aB3/xY9zK2mP7qR/tW"


# ======================================================================
# KNOWN GAP -- documented, not fixed this round
# ======================================================================

# [REVIEW] a credential embedded in a URI. The value heuristic is silenced by
# the URI shape; the secret-named TARGET still yields REVIEW via trigger A.
# Parsing credentials out of URIs is a separate concern.
secret_url = "https://u:p@host"


# ======================================================================
# ITEM 3 -- structured non-secret values (shape gate part two)
# ======================================================================

# [silent] user-agent shape
ua = "MyApp/2.1 (compatible; build 4471)"

# [silent] version string
version = "1.4.2-rc1"

# [silent] key=value log format
log_fmt = "level=info msg=started port=8080"

# [REVIEW] trigger A is UNAFFECTED by the gate: a secret-named target holding a
# structured value still reviews via the NAME, exactly as with the URL gate.
secret_version = "2.1.0"


# ======================================================================
# ITEM 5 -- credential-format prefix assembled with a variable
# ======================================================================

def assemble(env, suffix, tok, host, port, name, domain, user):
    # [REVIEW] known prefix + variable
    a = "sk-live-" + suffix
    b = f"sk-live-{env}"
    c = f"AKIA{suffix}"
    d = "ghp_" + tok
    # [silent] ordinary string building -- no credential prefix
    e = "user-" + name
    f = f"{host}:{port}"
    g = "https://" + domain
    h = f"hello {user}"
    return a, b, c, d, e, f, g, h
