"""Test corpus for detector 006 (ECB cipher mode).

Each case is labelled with its expected verdict.
Do not edit this file to make the detector pass.
"""

from Crypto.Cipher import AES, DES
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes


# ======================================================================
# HIGH -- confirmed ECB
# ======================================================================

# [HIGH] the canonical PyCryptodome form
def encrypt_aes(key, data):
    return AES.new(key, AES.MODE_ECB).encrypt(data)


# [HIGH] a different cipher -- matching is on the MODE, not the algorithm
def encrypt_des(key, data):
    return DES.new(key, DES.MODE_ECB).encrypt(data)


# [HIGH] the cryptography library idiom
def build_cipher(key):
    return Cipher(algorithms.AES(key), modes.ECB())


# [HIGH] assigned rather than used inline
def make_cipher(k):
    cipher = AES.new(k, AES.MODE_ECB)
    return cipher


# ======================================================================
# REVIEW -- unconfirmable (mode comes from a variable)
# ======================================================================

# [REVIEW] the tool cannot read the runtime value of `mode`
def encrypt_with_mode(key, data, mode):
    return AES.new(key, mode).encrypt(data)


# ======================================================================
# SILENT -- confirmed NOT ECB
# ======================================================================

# [silent] CBC
def encrypt_cbc(key, data, iv):
    return AES.new(key, AES.MODE_CBC, iv).encrypt(data)


# [silent] GCM
def encrypt_gcm(key, data):
    return AES.new(key, AES.MODE_GCM).encrypt(data)


# [silent] cryptography with CBC
def build_cbc_cipher(key, iv):
    return Cipher(algorithms.AES(key), modes.CBC(iv))


# ======================================================================
# ACCEPTED FALSE POSITIVE -- documented, deliberately NOT exempted
# ======================================================================

# [HIGH -- accepted false positive] ECB over a SINGLE block of already-random
# data (wrapping a key with a KEK) is rare, expert-level and occasionally
# legitimate. It still flags: a reviewer should glance at any ECB use.
def wrap_key(kek, key_material):
    return AES.new(kek, AES.MODE_ECB).encrypt(key_material)
