"""Test corpus for detector 005 (disabled TLS certificate verification).

Each case is labelled with its expected verdict.
Do not edit this file to make the detector pass.
"""

import ssl

import httpx
import requests

session = requests.Session()
CA_BUNDLE = "/etc/ssl/certs/ca.pem"


# ======================================================================
# HIGH -- the bug, in non-test code
# ======================================================================

# [HIGH] the canonical form
def fetch_status(url):
    return requests.get(url, verify=False)


# [HIGH] on a session, with other keywords present
def push_payload(url, d):
    return session.post(url, data=d, verify=False)


# [HIGH] a different library -- matching is library-agnostic
def fetch_via_httpx(url):
    return httpx.get(url, verify=False)


# [HIGH] unverified SSL context at the call site
def make_context():
    return ssl._create_unverified_context()


# [HIGH] the process-wide form -- worse: it disables verification globally
def disable_everywhere():
    ssl._create_default_https_context = ssl._create_unverified_context


# [HIGH] CERT_NONE assigned to a context
def relax(context):
    context.verify_mode = ssl.CERT_NONE
    return context


# ======================================================================
# REVIEW -- unconfirmable value (fail loud, do not guess)
# ======================================================================

# [REVIEW] verify comes from a variable
def fetch_with_flag(url, flag):
    return requests.get(url, verify=flag)


# [REVIEW] verify is None
def fetch_with_none(url):
    return requests.get(url, verify=None)


# ======================================================================
# SILENT -- correct or legitimate
# ======================================================================

# [silent] explicit True is the correct default
def fetch_verified(url):
    return requests.get(url, verify=True)


# [silent] omitted entirely -- verification is on by default
def fetch_default(url):
    return requests.get(url)


# [silent] a custom CA bundle path is legitimate
def fetch_custom_ca(url):
    return requests.get(url, verify="/etc/ca.pem")


# [silent] a variable holding a CA path is still a string at runtime, but the
# detector cannot know that -- this is the REVIEW case above, not silent.


# ======================================================================
# ACCEPTED FALSE POSITIVE -- documented, deliberately NOT exempted
# ======================================================================

# [HIGH -- accepted false positive] `verify` here means "check the signature",
# nothing to do with TLS. Library-agnostic matching flags it. Missing a real
# TLS bypass is worse than this rare false flag.
def parse_document(blob):
    return decode_document(blob, verify=False)


def decode_document(blob, verify=True): ...


# ======================================================================
# SHAPE 4 -- attribute assignment (the commonest production form)
# ======================================================================

# [HIGH] a session with verification switched off for every request it makes
def build_session():
    s = requests.Session()
    s.verify = False
    return s


# [HIGH] on a module-level session object
def disable_on_module_session():
    session.verify = False


# [REVIEW] unconfirmable value on the attribute form
def session_from_flag(flag):
    s = requests.Session()
    s.verify = flag
    return s


# [silent] explicit True on the attribute form
def session_verified():
    s = requests.Session()
    s.verify = True
    return s


# [REVIEW] a VARIABLE holding a CA path. My first label said silent -- that was
# wrong: the tool cannot tell a variable holding "/etc/ca.pem" from one holding
# False, so the stated rule (variable -> unconfirmable) makes this REVIEW.
def session_custom_ca():
    s = requests.Session()
    s.verify = CA_BUNDLE_PATH
    return s


# [silent] a string literal CA path
def session_literal_ca():
    s = requests.Session()
    s.verify = "/etc/ca.pem"
    return s


# ======================================================================
# SHAPE 5 -- kwargs unpacking
# ======================================================================

# [HIGH] a LITERAL dict is readable, so it is read
def fetch_literal_kwargs(url):
    return requests.get(url, **{"verify": False})


# [silent] a VARIABLE dict cannot be read -- disclosed in LIMITS, not flagged
def fetch_variable_kwargs(url, config):
    return requests.get(url, **config)


CA_BUNDLE_PATH = "/etc/ssl/certs/ca.pem"
