"""Test corpus for detector 001 v2 (swallowed exception).

Both axes crossed. Each function is labelled with its expected verdict.
Do not edit this file to make the detector pass.
"""

import logging

log = logging.getLogger(__name__)
logger = log


# ======================================================================
# BROAD x SILENT  -> expected HIGH
# ======================================================================

# [HIGH] except Exception: return None
def fetch_price(symbol):
    try:
        return lookup(symbol)
    except Exception:
        return None


# [HIGH] bare except: pass
def sync_ledger():
    try:
        push_entries()
    except:
        pass


# [HIGH] except BaseException: return
def close_position(pos):
    try:
        submit(pos)
    except BaseException:
        return


# [HIGH] except Exception: ...   (Ellipsis body)
def refresh_book(book):
    try:
        book.refresh()
    except Exception:
        ...


# [HIGH] except (Exception, KeyError): pass   (tuple containing a broad name)
def resolve_route(key):
    try:
        return TABLE[key]
    except (Exception, KeyError):
        pass


# ======================================================================
# BROAD x LOG-NO-RERAISE  -> expected MEDIUM
# ======================================================================

# [MEDIUM] except Exception: log(e); return None
def settle(order):
    try:
        return clear(order)
    except Exception as e:
        log.exception("settle failed: %s", e)
        return None


# [MEDIUM] except (BaseException, OSError) as e: logger.error(e)
def flush_journal(path):
    try:
        write_journal(path)
    except (BaseException, OSError) as e:
        logger.error("journal flush failed: %s", e)


# ======================================================================
# HANDLED / NOT BROAD  -> expected NOT FLAGGED (silent)
# ======================================================================

# [not flagged] broad, but logs and re-raises -- the error propagates
def parse_amount(raw):
    try:
        return int(raw)
    except Exception as e:
        log.error("bad amount %r: %s", raw, e)
        raise


# [not flagged] narrow catch -- not broad
def read_nonce(raw):
    try:
        return int(raw)
    except ValueError:
        return None


# [not flagged] tuple with no broad name -- not broad
def decode_frame(buf):
    try:
        return unpack(buf)
    except (ValueError, TypeError):
        pass


# [not flagged] broad, but the body does real work -- no discard
def load_config(path):
    try:
        return read_json(path)
    except Exception:
        fallback = default_config()
        record_degraded_mode(path)
        return fallback


TABLE = {}


def lookup(symbol): ...
def push_entries(): ...
def submit(pos): ...
def clear(order): ...
def write_journal(path): ...
def unpack(buf): ...
def read_json(path): ...
def default_config(): ...
def record_degraded_mode(path): ...


# ======================================================================
# BROAD x UNCLASSIFIED BODY  -> expected REVIEW   (v3)
# ======================================================================

# [REVIEW] broad catch, assignment body: no re-raise, no discard, no call
class Feed:
    def poll(self):
        try:
            self.tick()
        except Exception:
            self.state = "broken"

    def tick(self): ...


# [REVIEW] broad catch, two NON-logging discarded calls, no re-raise, no trace
def teardown(session):
    try:
        session.commit()
    except Exception:
        some_cleanup()
        undo()


# [REVIEW] broad tuple catch, mixed statement shapes
def replay_chunk(chunk):
    try:
        return apply_chunk(chunk)
    except (BaseException, IOError):
        seen = mark_seen(chunk)
        if seen:
            bump_counter()
        del seen


# [not flagged] NARROW catch with an odd body -- out of scope, never REVIEW
def bump_retry(state):
    try:
        state.attempt()
    except TimeoutError:
        state.retries += 1
        state.last = "timeout"


# [not flagged] NARROW tuple catch with an odd body -- out of scope, never REVIEW
def coerce_qty(raw):
    try:
        return int(raw)
    except (ValueError, TypeError):
        qty = 0
        note_bad_input(raw)
        return qty


def some_cleanup(): ...
def undo(): ...
def apply_chunk(chunk): ...
def mark_seen(chunk): ...
def bump_counter(): ...
def note_bad_input(raw): ...


# ======================================================================
# v4 -- name-based logging recognition
# ======================================================================

# [MEDIUM] recognized log call + a non-logging cleanup call: the trace survives
def commit_batch(batch):
    try:
        return batch.commit()
    except Exception as e:
        logger.error("batch commit failed: %s", e)
        some_cleanup()
        return None


# [REVIEW] two non-logging calls: no trace, unclassified work
def abort_txn(txn):
    try:
        txn.apply()
    except Exception:
        rollback()
        retry()


def rollback(): ...
def retry(): ...


# ======================================================================
# DELEGATION -- structural remediation recognition
# ======================================================================

from external_guards import external_guard   # not defined in this corpus


class ProgrammingError(Exception):
    pass


def guard(e):
    """Verified re-raiser: CONDITIONAL raise counts."""
    if isinstance(e, ProgrammingError):
        raise e


def always_guard(e):
    """Verified re-raiser: unconditional."""
    raise e


def bug_guard_style(e, what):
    """_bug_guard shape: isinstance test, log, then raise."""
    if isinstance(e, ProgrammingError) and _ours(e):
        log.error("PROGRAMMING ERROR while %s", what)
        raise e


def fake_guard(e):
    """Guard-looking, but never re-raises. Must NOT be trusted."""
    log.error("swallowed: %s", e)


def _ours(e): ...


# [not flagged] delegates to a verified conditional re-raiser
def delegates_to_guard(job):
    try:
        job.run()
    except Exception as e:
        guard(e)
        return None


# [not flagged] delegates to an unconditional re-raiser
def delegates_to_always(job):
    try:
        job.run()
    except Exception as e:
        always_guard(e)


# [not flagged] _bug_guard-style conditional isinstance-then-raise
def delegates_to_bug_guard(job):
    try:
        job.run()
    except Exception as e:
        bug_guard_style(e, "delegates_to_bug_guard")
        return None


# [REVIEW] FAKE GUARD -- resolvable but never raises, so the handler still
# swallows. Label corrected from HIGH: delegate-to-nonraiser + return None is
# genuinely unclassifiable, and REVIEW is the honest verdict.
def delegates_to_fake_guard(job):
    try:
        job.run()
    except Exception as e:
        fake_guard(e)
        return None


# [REVIEW] helper is imported, not resolvable -- cannot verify, must not trust
def delegates_to_external(job):
    try:
        job.run()
    except Exception as e:
        external_guard(e)
        return None


# ======================================================================
# NON-CANDIDATES -- builtins and library calls are NOT delegation.
# These are judged by their BODY, under a true label.
# ======================================================================

# [MEDIUM] type(e) is a builtin, not a guard; body logs -> log-and-swallow
def builtin_then_log(job):
    try:
        job.run()
    except Exception as e:
        msg = type(e).__name__
        log.warning(msg)


# [REVIEW unclassified] out.put is an attribute call on a non-self object
# that resolves to no def -- a library call, not remediation
def queue_the_error(job, out):
    try:
        job.run()
    except Exception as e:
        out.put(('fail', str(e)))


# [REVIEW unclassified] str/.strip are non-candidates; body is assign +
# return None, which is not all-discard (the Assign is real work)
def stringify_then_discard(job):
    try:
        job.run()
    except Exception as e:
        x = str(e).strip()
        return None
