"""Test corpus for detector 004 (insecure random for a security purpose).

Each case is labelled with its expected verdict.
Do not edit this file to make the detector pass.
"""

import os
import random
import secrets

import numpy as np

CHARS = "abcdefghijklmnopqrstuvwxyz"


# ======================================================================
# HIGH -- a strong signal on some axis
# ======================================================================

# [HIGH] high-precision target name
def issue_credential():
    token = random.randint(0, 999999)
    return token


# [HIGH] high-precision target name
def make_login():
    password = random.choice(CHARS)
    return password


# [HIGH] high-precision ENCLOSING FUNCTION name, no target name at all
def generate_secret():
    return random.random()


# ======================================================================
# REVIEW -- medium signal, nothing strong
# ======================================================================

# [REVIEW] collision-prone target name (shape also fires, max wins -> REVIEW)
def build_material():
    key = random.randbytes(16)
    return key


# [REVIEW] collision-prone enclosing function name
def make_nonce():
    return random.getrandbits(64)


# [REVIEW] collision-prone target name
def derive():
    salt = random.randbytes(8)
    return salt


# ======================================================================
# LOW -- shape only, no name signal anywhere
# ======================================================================

# [LOW] randbytes with no secret target and no security-named function
def gen():
    return random.randbytes(32)


# [LOW] getrandbits in a non-security function, innocent target name
def compute_width():
    x = random.getrandbits(128)
    return x


# ======================================================================
# SILENT BY DESIGN -- insecure RNG, but no signal on any axis
# ======================================================================

# [silent] a probability
def coin_flip():
    probability = random.random()
    return probability > 0.5


# [silent] sampling an index
def pick(items):
    idx = random.randint(0, len(items) - 1)
    return items[idx]


# [silent] shuffling a non-secret list
def reorder(playlist):
    random.shuffle(playlist)
    return playlist


# ======================================================================
# EXEMPT -- must produce nothing
# ======================================================================

# [exempt] secrets is the fix
def issue_token_safely():
    token = secrets.token_hex(16)
    return token


# [exempt] os.urandom is the fix
def make_key_safely():
    key = os.urandom(32)
    return key


# [exempt] SystemRandom is a CSPRNG -- the safe form inside the dangerous module
def secure_pick():
    secret = random.SystemRandom().randint(0, 9)
    return secret


# ======================================================================
# v2 -- numpy LEGACY (direct, module-level), treated like stdlib direct
# ======================================================================

# [HIGH] high-precision target + .bytes shape
def issue_np_token():
    token = np.random.bytes(16)
    return token


# [REVIEW] collision-prone target, no shape signal (randint is a sim shape)
def build_np_material():
    key = np.random.randint(0, 2**32)
    return key


# [silent] simulation noise -- no signal on any axis
def make_noise():
    x = np.random.rand(100)
    return x


# ======================================================================
# v2 -- numpy MODERN (stored instance). Creation taints, USE flags.
# ======================================================================

# [HIGH] tracked instance, high-precision target, .bytes shape
def issue_np_token_modern():
    rng = np.random.default_rng()
    token = rng.bytes(16)
    return token


# [silent] tracked instance, but a Monte Carlo draw with no name signal
def simulate():
    rng = np.random.default_rng()
    sample = rng.normal(0, 1, 1000)
    return sample


# module-level generator, inherited by the nested def below
MODULE_RNG = np.random.default_rng()


# [REVIEW] collision-prone function name AND target; instance inherited
def make_key():
    key = MODULE_RNG.integers(0, 2**32)
    return key


# ======================================================================
# v2 -- stdlib instance form (same tracking mechanism)
# ======================================================================

# [HIGH] tracked stdlib instance, high-precision target
def issue_token_instance():
    r = random.Random()
    token = r.randint(0, 999)
    return token


# ======================================================================
# v2 -- ESCAPE cases: tracking ends, findings go SILENT by design
# ======================================================================

# [silent] alias -- r2 is not tracked, and rng stops being tracked
def aliased():
    rng = np.random.default_rng()
    r2 = rng
    key = r2.bytes(16)
    return key


# [silent] stored on an attribute -- not tracked
class Holder:
    def setup(self):
        rng = np.random.default_rng()
        self.rng = rng

    def use_later(self):
        token = self.rng.bytes(16)
        return token


# [silent] passed as an argument -- tracking ends
def passed_away(sink):
    rng = np.random.default_rng()
    sink(rng)
    secret = rng.bytes(16)
    return secret


# ======================================================================
# COMBINATION rule -- catastrophe stays HIGH, bare private demotes
# ======================================================================

# [HIGH] private_key target (combination high) + randbytes shape
def make_private_key():
    private_key = random.randbytes(32)
    return private_key


# [REVIEW] is_private: bare 'private' -> collision-prone
def seed_warehouse():
    is_private = random.choice([True, False])
    return is_private


# ======================================================================
# ITEM 4 -- module-level import-alias resolution
# ======================================================================

import random as rnd
from random import randint as ri


# [HIGH] aliased module + secret target
def issue_aliased_token():
    token = rnd.randint(0, 999)
    return token


# [HIGH] aliased from-import + secret target
def issue_aliased_ri():
    token = ri(0, 999)
    return token


# [silent] aliased module, NO security context
def sample_aliased():
    x = rnd.random()
    return x
