"""Test corpus for detector 002 (non-constant-time comparison of secrets).

Detector 002 is HIGH-only: it answers "is a secret compared in
non-constant-time?" and nothing else. The former LOW cases are KEPT here
deliberately, relabelled [no finding], so the corpus asserts their silence
rather than hiding it by deletion.

Each case is labelled with its expected verdict.
Do not edit this file to make the detector pass.
"""

import hmac
import secrets


# ======================================================================
# HIGH -- suspicious name as an ==/!= operand, not exempt
# ======================================================================

# [HIGH] classic token compare
def verify_token(user_token, real_token):
    if user_token == real_token:
        return True
    return False


# [HIGH] MAC compare with !=
def check_mac(computed_mac, expected_mac):
    if computed_mac != expected_mac:
        return False
    return True


# [HIGH] hashed-then-compared is still the bug
def login(password, submitted):
    if password == submitted:
        return "ok"
    return "denied"


# [HIGH] digest compare
def verify_digest(digest, expected_digest):
    if digest == expected_digest:
        return True
    return False


# [HIGH] signature compare
def check_sig(sig, provided_sig):
    if sig == provided_sig:
        return True
    return False


# ======================================================================
# EXEMPT / not HIGH
# ======================================================================

# [not flagged] constant-time compare -- this is the FIX, not the bug
def verify_safely(token, real):
    return hmac.compare_digest(token, real)


# [not flagged] secrets.compare_digest -- the other real primitive
def verify_safely_secrets(token, real):
    return secrets.compare_digest(token, real)


# [HIGH inside the def] a LOOK-ALIKE compare_digest: same name, not
# constant-time. v1 trusted this by name; v2 does not.
def compare_digest(secret_a, secret_b):
    return secret_a == secret_b


# [call site NOT exempt] operands handed to the look-alike stay visible
def verify_lookalike(token, real):
    return compare_digest(token, real)


# [no finding] presence check against None -- not a timing leak (was LOW)
def has_token(token):
    if token == None:
        return False
    return True


# [no finding] dict subscript -- the innocent 'key' use (was LOW)
def read_setting(config, key):
    return config[key]


# [no finding] sort keyword argument named 'key' (was LOW)
def order_items(items):
    return sorted(items, key=get_id)


# [not flagged] username is not a suspicious name
def is_admin(username):
    if username == "admin":
        return True
    return False


# ======================================================================
# Former LOW cases -- secret name present, no equality compare.
# Detector 002 is HIGH-only, so all of these must now be SILENT.
# ======================================================================

# [no finding] assignment target (was LOW)
def refresh():
    token = fetch_token()
    return token


# [no finding] parameter name (was LOW)
def sign(secret):
    return derive(secret)


def get_id(item): ...
def fetch_token(): ...
def derive(value): ...


# ======================================================================
# v4 -- constant gate, precision tiering, self.attr coverage
# ======================================================================

INVALID_TOKEN = "invalid"
PRIVATE_KEY = "private"
PUBLIC_KEY = "public"


# [EXEMPT] string-literal operand -- a mode/config check, not a timing leak
def pick_derivation(key_derivation):
    if key_derivation == "concat":
        return 1
    return 2


# [LOW] ALL-CAPS constant on one side -- down-tiered, not exempted
def check_error_code(token):
    if token == INVALID_TOKEN:
        return "bad"
    return "ok"


# [LOW] ALL-CAPS on both sides
def compare_meta_constants():
    return PRIVATE_KEY == PUBLIC_KEY


# [HIGH] self.attr on the left -- v3 MISSED this entirely
class Verifier:
    def check(self, other):
        if self.secret_key == other:
            return True
        return False

    # [HIGH] self.attr on both sides
    def check_both(self):
        if self.token == self.expected:
            return True
        return False


# [HIGH] obj.attr classified on the attribute name, not the base
def check_obj(request, expected):
    if request.token == expected:
        return True
    return False


# ======================================================================
# COMBINATION rule -- the catastrophe path (untested by real code)
# ======================================================================

# [HIGH] private_key: private(collision) + key(collision) -> combination high
def verify_private_key(stored_private_key, submitted_private_key):
    if stored_private_key == submitted_private_key:
        return True
    return False


# [REVIEW] bare 'private' only -- demoted to collision-prone
def metadata_changed(old_private_metadata, new_private_metadata):
    return old_private_metadata != new_private_metadata
