"""Test corpus for detector 007 (weak hash used for security).

Each case is labelled with its expected verdict.
Do not edit this file to make the detector pass.
"""

import hashlib


# ======================================================================
# HIGH -- a security context
# ======================================================================

# [HIGH] secret input AND security target
def store_credentials(password):
    password_hash = hashlib.md5(password.encode())
    return password_hash.hexdigest()


# [HIGH] secret input
def sign_payload(secret_key):
    sig = hashlib.sha1(secret_key)
    return sig.hexdigest()


# [HIGH] security-named function
def hash_password(pw):
    return hashlib.md5(pw).hexdigest()


# [HIGH] the string-named form, fed a secret via update()
def fingerprint(api_key):
    h = hashlib.new("md5")
    h.update(api_key)
    return h.hexdigest()


# ======================================================================
# REVIEW -- a collision-prone signal only
# ======================================================================

# [REVIEW] collision-prone target, no secret input
def summarize(x):
    key_digest = hashlib.md5(x)
    return key_digest.hexdigest()


# ======================================================================
# SILENT -- innocent use (the flood test)
# ======================================================================

# [silent] a cache key
def cache_for(url):
    cache_key = hashlib.md5(url.encode()).hexdigest()
    return cache_key


# [silent] a file checksum
def checksum(file_bytes):
    file_hash = hashlib.sha1(file_bytes).hexdigest()
    return file_hash


# [silent] a dedup id
def dedup(record_bytes):
    dedup_id = hashlib.md5(record_bytes).hexdigest()
    return dedup_id


# [silent] the developer's explicit declaration
def bucket(data):
    return hashlib.md5(data, usedforsecurity=False).hexdigest()


# [silent] SHA-256 is not weak -- not this detector's concern
def store_strong(password):
    return hashlib.sha256(password).hexdigest()


# ======================================================================
# T1-4: an UNCONFIRMABLE algorithm -- hashlib.new(<variable>)
# ======================================================================

# [REVIEW] security context fires (secret input + secret target), but the
# algorithm cannot be read -- so it is surfaced, never asserted weak.
def derive_from(password, algo):
    password_hash = hashlib.new(algo)
    password_hash.update(password)
    return password_hash.hexdigest()


# [silent] NO security context -- a checksum with a configurable algorithm is
# ordinary, and flagging it would flood.
def checksum_with(file_bytes, algo):
    result = hashlib.new(algo)
    result.update(file_bytes)
    return result.hexdigest()


# [REVIEW] my first version of the cell above named the target `digest_of_file`
# and I labelled it silent -- that was wrong: 'digest' is collision-prone, so a
# context DOES fire. Kept as its own cell because it demonstrates the weakness
# already recorded in this detector's LIMITS (collision-prone names are exactly
# what innocent checksum variables are called).
def checksum_named_digest(file_bytes, algo):
    digest_of_file = hashlib.new(algo)
    digest_of_file.update(file_bytes)
    return digest_of_file.hexdigest()
