"""Test corpus for detector 003 (secret reaches a sink).

Each case is labelled with its expected verdict.
Do not edit this file to make the detector pass.
"""

import logging

logger = logging.getLogger(__name__)


# ======================================================================
# HIGH -- a secret passed directly as a sink argument
# ======================================================================

# [HIGH] bare log call
def leak_via_log(token):
    log(token)


# [HIGH] print
def leak_via_print(api_key):
    print(api_key)


# [HIGH] attribute call on a logger
def leak_via_logger(secret):
    logger.error(secret)


# [HIGH] nested attribute call
class Service:
    def leak_via_self_log(self, password):
        self.log.debug(password)


# [HIGH] exception message, secret passed directly
def leak_via_raise(token):
    raise ValueError(token)


# [HIGH] exception message, secret inside an f-string (direct)
def leak_via_fstring_raise(token):
    raise RuntimeError(f"key={token}")


# ======================================================================
# REVIEW -- same-variable indirect flow
# ======================================================================

# [REVIEW] msg receives an f-string carrying a secret, msg reaches a sink
def leak_via_message(token):
    msg = f"key={token}"
    log(msg)


# [REVIEW] detail receives a secret, detail reaches an exception message
def leak_via_detail(secret):
    detail = secret
    raise ValueError(detail)


# ======================================================================
# SILENT -- must produce nothing
# ======================================================================

# [silent] no secret anywhere
def log_static():
    log("static message")


# [silent] username is not a secret name
def log_username(username):
    log(username)


# [silent] rename -- out of scope for v1, silent by design
def rename_then_log(token):
    x = token
    y = x
    log(y)


# [silent] a comparison is detector #2's job, not a sink
def compare_only(token, real):
    return token == real


# [silent] subscript, no sink
def read_setting(config, key):
    return config[key]


def log(message): ...


# ======================================================================
# v2 -- precision x directness. Four cells, plus the tie cases.
# ======================================================================

# --- HIGH: high-precision + direct ---

# [HIGH] password direct to an exception message
def leak_password_raise(password):
    raise ValueError(password)


# [HIGH] secret_key -- TIE CASE: 'secret' is high-precision, beats 'key'
def leak_secret_key(secret_key):
    log(secret_key)


# [HIGH] private_key -- 'private' is a high-precision component
def leak_private_key(private_key):
    log(private_key)


# [HIGH] signing_key -- 'signing' is a high-precision component
def leak_signing_key(signing_key):
    log(signing_key)


# [HIGH] bare hmac -- high-precision, no innocent meaning
def leak_hmac(hmac):
    log(hmac)


# --- REVIEW: high-precision + indirect ---

# [REVIEW] secret flows through a variable, then to a sink
def leak_secret_indirect(secret):
    msg = f"{secret}"
    log(msg)


# --- REVIEW: collision-prone + direct ---

# [REVIEW] digest direct to a sink (was HIGH before the precision split)
def print_digest(digest):
    log(digest)


# [REVIEW] hash_value direct to a sink
def print_hash(hash_value):
    print(hash_value)


# [REVIEW] sort_key -- TIE CASE: collision-prone only
def print_sort_key(sort_key):
    log(sort_key)


# [REVIEW] partition_key -- TIE CASE: collision-prone only
def print_partition_key(partition_key):
    log(partition_key)


# --- LOW: collision-prone + indirect ---

# [LOW] digest flows through a variable, then to a sink
def print_digest_indirect(digest):
    h = f"{digest}"
    log(h)


# ======================================================================
# COMBINATION rule -- catastrophe stays HIGH, bare private demotes
# ======================================================================

# [HIGH] signing_key: signing + key -> combination high, direct to sink
def leak_signing_key(signing_key):
    log(signing_key)


# [REVIEW] private_metadata: bare 'private' -> collision, direct to sink
def leak_private_metadata(private_metadata):
    log(private_metadata)
